### PR TITLE
Create fr_FR.lang

### PR DESCRIPTION
**Pull request by Mazdallier**

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Any reason you have only translated the blocks, and some of the items ? ^^

**Comment by MineMaarten** [comment]
I can imagine it being a lot of work, and this is at least a start :).

**Comment by Mazdallier** [comment]
Yes of course ! And my time is count...

**Comment by Mazdallier** [comment]
i translate all except gui. I shoud take a look in game with MultiMC when the mode will be upgraded.

**Pull request merged**
